name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: product-service
      DOCKER_USERNAME: pooja06bhosale

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:${{ github.ref_name }} .

      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME:${{ github.ref_name }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/product-v1.yaml
          kubectl apply -f kubernetes/hpa-v1.yaml
          kubectl apply -f kubernetes/product-ingress.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Run integration test
        run: curl --fail http://localhost/v1/health
